# services to handle doctrine extensions
# import it in config.yml
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            timestampable: true
            translatable: true
