
api_oauth2_decks:
    path: /decks
    methods: [GET]
    defaults:
        _controller: AppBundle:Oauth2:listDecks

api_oauth2_load_deck:
    path: /deck/load/{id}
    methods: [GET]
    defaults:
        _controller: AppBundle:Oauth2:loadDeck
    requirements:
        id: \d+

api_oauth2_new_deck:
    path: /deck/new
    methods: [POST]
    defaults:
        _controller: AppBundle:Oauth2:newDeck

api_oauth2_save_deck:
    path: /deck/save/{id}
    methods: [PUT]
    defaults:
        _controller: AppBundle:Oauth2:saveDeck
    requirements:
        id: \d+

api_oauth2_upgrade_deck:
    path: /deck/upgrade/{id}
    methods: [PUT]
    defaults:
        _controller: AppBundle:Oauth2:upgradeDeck
    requirements:
        id: \d+

api_oauth2_publish_deck:
    path: /deck/publish/{id}
    methods: [PUT]
    defaults:
        _controller: AppBundle:Oauth2:publishDeck
    requirements:
        id: \d+
