admin_encounter:
    path:  /
    defaults: { _controller: "AppBundle:Encounter:index" }

admin_encounter_show:
    path:  /{id}/show
    defaults: { _controller: "AppBundle:Encounter:show" }

admin_encounter_new:
    path:  /new
    defaults: { _controller: "AppBundle:Encounter:new" }

admin_encounter_create:
    path:  /create
    defaults: { _controller: "AppBundle:Encounter:create" }
    methods: [ post ]

admin_encounter_edit:
    path:  /{id}/edit
    defaults: { _controller: "AppBundle:Encounter:edit" }

admin_encounter_update:
    path:  /{id}/update
    defaults: { _controller: "AppBundle:Encounter:update" }
    methods: [ post, put ]

admin_encounter_delete:
    path:  /{id}/delete
    defaults: { _controller: "AppBundle:Encounter:delete" }
    methods: [ post, delete ]
