AppBundle\Entity\Cardset:
    type: entity
    table: Cardset
    repositoryClass: AppBundle\Repository\CardsetRepository
    oneToMany:
        cards:
            targetEntity: Card
            orderBy: {'position':'ASC'}
            mappedBy: card_set
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 1024
            nullable: false
            gedmo:
                - translatable
    uniqueConstraints:
        encounter_code_idx:
            columns: [ code ]
            