AppBundle\Entity\Decklist:
    type: entity
    table: decklist
    manyToOne:
        user:
            targetEntity: User
            nullable: false
            inversedBy: decklists
            joinColumn:
                name: user_id
                referencedColumnName: id
        character:
            targetEntity: Card
            nullable: false
            joinColumn:
                name: card_id
                referencedColumnName: id
        taboo:
            targetEntity: Taboo
            nullable: true
            joinColumn:
                name: taboo_id
                referencedColumnName: id
        lastPack:
            targetEntity: Pack
            nullable: false
            joinColumn:
                name: last_pack_id
                referencedColumnName: id
        parent:
            targetEntity: Deck
            nullable: true
            inversedBy: children
            joinColumn:
                name: parent_deck_id
                referencedColumnName: id
        precedent:
            targetEntity: Decklist
            orderBy: { 'dateCreation': 'ASC' }
            nullable: true
            inversedBy: successors
            joinColumn:
                name: precedent_decklist_id
                referencedColumnName: id
                onDelete: SET NULL
        tournament:
            targetEntity: Tournament
            nullable: true
            inversedBy: decklists
            joinColumn:
                name: tournament_id
                referencedColumnName: id
    oneToMany:
        slots:
            targetEntity: Decklistslot
            mappedBy: decklist
            cascade: ["persist","remove"]
        comments:
            targetEntity: Comment
            orderBy: { 'dateCreation': 'ASC' }
            mappedBy: decklist
            cascade: ["persist","remove"]
        successors:
            targetEntity: Decklist
            orderBy: { 'dateCreation': 'ASC' }
            mappedBy: precedent
        children:
            targetEntity: Deck
            mappedBy: parent
    oneToOne:
        nextDeck:
            targetEntity: Decklist
            nullable: true
            cascade: ["persist","remove"]            
            joinColumn:
                name: next_deck
                referencedColumnName: id
                onDelete: CASCADE
        previousDeck:
            targetEntity: Decklist
            nullable: true
            cascade: ["persist","remove"]
            joinColumn:
                name: previous_deck
                referencedColumnName: id
                onDelete: CASCADE
    manyToMany:
        favorites:
            targetEntity: User
            inversedBy: favorites
            joinTable:
                name: favorite
                cascade: ["persist","remove"]
                joinColumns:
                    decklist_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
        votes:
            targetEntity: User
            inversedBy: votes
            joinTable:
                name: vote
                cascade: ["persist","remove"]
                joinColumns:
                    decklist_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        nameCanonical:
            type: string
            length: 255
            column: name_canonical
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
        descriptionMd:
            type: text
            nullable: true
            column: description_md
        tags:
            type: string
            length: 4000
            nullable: true
        descriptionHtml:
            type: text
            nullable: true
            column: description_html
        xp:
            type: integer
            nullable: true
        xpSpent:
            type: integer
            nullable: true
        xpAdjustment:
            type: integer
            nullable: true
        signature:
            type: string
            length: 32
        nbVotes:
            type: integer
            column: nb_votes
        nbFavorites:
            type: integer
            column: nb_favorites
        nbComments:
            type: integer
            column: nb_comments
        version:
            type: string
            length: 8
        exiles:
            type: string
            length: 255
            nullable: true
        meta:
            type: text
            nullable: true