AppBundle\Entity\PackOwnership:
  type: entity
  table: pack_ownership
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  manyToOne:
    user:
      targetEntity: AppBundle\Entity\User
      joinColumn:
        name: user_id
        referencedColumnName: id
        nullable: false
    pack:
      targetEntity: AppBundle\Entity\Pack
      joinColumn:
        name: pack_id
        referencedColumnName: id
        nullable: false
