AppBundle\Entity\PackOwnership:
    type: entity
    table: pack_ownership
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        userId:
            type: integer
            nullable: false
        packId:
            type: integer
            nullable: false