AppBundle\Entity\Packtype:
    type: entity
    table: Packtype
    repositoryClass: AppBundle\Repository\PacktypeRepository
    gedmo:
        translation:
            locale: locale
    oneToMany:
        packs:
            targetEntity: Pack
            orderBy: {'position':'ASC'}
            mappedBy: pack_type
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: '1024'
            nullable: false
            gedmo:
                - translatable
    uniqueConstraints:
        type_code_idx:
            columns: [ code ]
